# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{attrtastic}
  s.version = "0.1.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Boruta Miroslaw"]
  s.date = %q{2010-01-03}
  s.description = %q{description}
  s.email = %q{boruta.miroslaw@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "attrtastic.gemspec",
     "lib/attrtastic.rb",
     "rails/init.rb",
     "test/helper.rb",
     "test/test_attribute.rb",
     "test/test_attributes.rb",
     "test/test_attrtastic.rb",
     "test/test_semantic_attributes_helper.rb"
  ]
  s.homepage = %q{http://github.com/MBO/attrtastic}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{summary}
  s.test_files = [
    "test/helper.rb",
     "test/test_attrtastic.rb",
     "test/test_attribute.rb",
     "test/test_semantic_attributes_helper.rb",
     "test/test_attributes.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<yard>, [">= 0"])
    else
      s.add_dependency(%q<yard>, [">= 0"])
    end
  else
    s.add_dependency(%q<yard>, [">= 0"])
  end
end

